### ISSUE TITLE
ContextErrorException in FieldTypeBase.php line 59

### ISSUE THREAD

**Issue by maleksandrov** [Bixie/pk-framework#2]
After update, I start receiving this error: 

### Notice: Undefined index: loadScript
1. in FieldTypeBase.php line 59
2. at ErrorHandler->handleError('8', 'Undefined index: loadScript', '/home/pagekit/public_html/packages/bixie/pk-framework/src/FieldType/FieldTypeBase.php', '59', array('scripts' => object(AssetManager))) in FieldTypeBase.php line 59
3. at FieldTypeBase->registerScripts(object(AssetManager)) in index.php line 44
4. at FrameworkModule->{closure}(object(Event), object(AssetManager))
5. at call_user_func_array(object(Closure), array(object(Event), object(AssetManager))) in EventDispatcher.php line 123
6. at EventDispatcher->trigger('view.scripts', array(object(AssetManager))) in PrefixEventDispatcher.php line 72
7. at PrefixEventDispatcher->trigger('scripts', array(object(AssetManager))) in View.php line 189
8. at View->trigger('scripts', array(object(AssetManager))) in ScriptHelper.php line 31
9. at ScriptHelper->Pagekit\View\Helper\{closure}(object(ViewEvent), object(View))
10. at call_user_func_array(object(Closure), array(object(ViewEvent), object(View))) in EventDispatcher.php line 123
11. at EventDispatcher->trigger(object(ViewEvent), array(object(View))) in PrefixEventDispatcher.php line 72
12. at PrefixEventDispatcher->trigger(object(ViewEvent), array(object(View))) in View.php line 189
13. at View->trigger(object(ViewEvent), array(object(View))) in DeferredHelper.php line 57
14. at DeferredHelper->Pagekit\View\Helper\{closure}(object(KernelEvent), object(Request), object(Response))
15. at call_user_func_array(object(Closure), array(object(KernelEvent), object(Request), object(Response))) in EventDispatcher.php line 123
16. at EventDispatcher->trigger(object(KernelEvent), array(object(Request), object(Response))) in HttpKernel.php line 175
17. at HttpKernel->handleResponse(object(Response)) in HttpKernel.php line 80
18. at HttpKernel->handle(object(Request)) in Application.php line 67
19. at Application->run() in app.php line 24
20. at require_once('/home/pagekit/public_html/app/system/app.php') in index.php line 40

The problem are coming from this part of the script, probably I need to contact Bixie team.

public function registerScripts ($scripts) {
        if ($this->type['loadScript']) {
            $script = $this->type['resource'] . '/fieldtype-' . $this->id . '.js';
            $scripts->register('fieldtype-' . $this->id, $script,
                array_merge(['~bixie-fieldtypes'], $this->type['dependancies']));
            return [];
        } else {
            return $this->type['dependancies'];
        }
}

## Technical Details

- Pagekit version: 1.0.11
- Webserver: Apache/2.2.3
- Database: 5.1.58
- PHP Version: 5.5.38

**Comment by tobbexiv** [comment]
Can you login to the admin panel? Then it would be good to know which version of the pk-framework extension do you have? Do you have any other Bixie extensions installed (e.g. Formmaker, Portfolio, ...)?

**Comment by maleksandrov** [comment]
Hi tobbexiv,

Unfortunately I cant login in the admin panel in the begging. After I comment this part of the script:
$script = $this->type['resource'] . '/fieldtype-' . $this->id . '.js';
$scripts->register('fieldtype-' . $this->id, $script,
array_merge(['~bixie-fieldtypes'], $this->type['dependancies']));
return [];
} else {
return $this->type['dependancies'];
}

I login whiteout any problem. 
I have installed all extensions from Bixie and only the framework causes some problems. 
The version of the pk-framework is 1.0.4.

Cheers,
Milen

**Comment by tobbexiv** [comment]
The framework is used by some of the other Bixie extensions, so it might be that the issue is in another extension. I tried to reproduce the issue in a test installation, but I was not able to do so. So this seems not to be a general problem. Maybe you can deactivate all bixie installations, uncomment the script part again and then activate them step by step starting from the framework? Then it might be more clear which extension is responsible for the error.

**Comment by maleksandrov** [comment]
OK, this is crazy, but now everything is working. I do exactly what you told me, and is working. I have no idea what causes this problem, but everything is OK. 
Thanks 👍 🥇

**Comment by tobbexiv** [comment]
Ok. That was not the result I expected. But great, that everything works fine for you again :)

Maybe you can close the two reports as I don't think ther is any chance that anyone will find the cause for this :)

**Comment by maleksandrov** [comment]
Me too, and I don't have any clue what cause this. But thanks 👍

**Comment by tobbexiv** [comment]
Deactivating / activating can trigger code execution. Maybe one of them corrected the error.

**Comment by maleksandrov** [comment]
Yeah, just like in WordPress.
